{% set name = "django-health-check" %}
{% set version = "3.18.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-health-check-{{ version }}.tar.gz
  sha256: 44552d55ae8950c9548d3b90f9d9fd5570b57446a19b2a8e674c82f993cb7a2c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - django >=2.2

test:
  imports:
    - health_check
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/revsys/django-health-check
  summary: Run checks on services like databases, queue servers, celery processes, etc.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
