# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-health-check
  version: "3.20.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_health_check-${{ version }}.tar.gz
  sha256: d630bd83508810ecb94dadf00c3f0e7952dbc472d9c7691aa4af868f44a04e89

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - flit-core >=3.2
    - flit-scm
    - wheel
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - django >=4.2
    - amqp
    - celery
    - kombu
    - psutil
    - redis-py

tests:
  - python:
      imports:
        - health_check
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  summary: Run checks on services like databases, queue servers, celery processes, etc.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/revsys/django-health-check

extra:
  recipe-maintainers:
    - rxm7706
