# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-health-check
  version: 4.0.3

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_health_check-${{ version }}.tar.gz
  sha256: 06ca4dc203ba28f6e269c49709d3c3e31b5bb9f9c5c08c98cdbd4bdd9a1bbdc1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - flit-core >=3.2
    - flit-scm
    - wheel
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - django >=5.2
    - dnspython >=2.0.0
    - redis-py
    - feedparser
    - python-confluent-kafka
    - celery
    - httpx
    - aio-pika
tests:
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - python -c "import django; from django.conf import settings; settings.configure(); django.setup(); import health_check"
      - pip check

about:
  summary: Monitor the health of your Django app and its connected services.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/codingjoe/django-health-check

extra:
  recipe-maintainers:
    - rxm7706
